// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRN222_Assm.Models;

#nullable disable

namespace PRN222_Assm.Migrations
{
    [DbContext(typeof(PrnassmContext))]
    [Migration("20250330105855_migr1")]
    partial class migr1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRN222_Assm.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("PRN222_Assm.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<bool>("isPresent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("PRN222_Assm.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("PRN222_Assm.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int?>("Subject")
                        .HasColumnType("int");

                    b.Property<int?>("Tearcher")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.HasIndex("Subject");

                    b.HasIndex("Tearcher");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("PRN222_Assm.Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Assignment")
                        .HasColumnType("float");

                    b.Property<double?>("Final")
                        .HasColumnType("float");

                    b.Property<double?>("Pt1")
                        .HasColumnType("float")
                        .HasColumnName("PT1");

                    b.Property<double?>("Pt2")
                        .HasColumnType("float")
                        .HasColumnName("PT2");

                    b.Property<double?>("Quiz")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Score", (string)null);
                });

            modelBuilder.Entity("PRN222_Assm.Models.Semmester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Semmester", (string)null);
                });

            modelBuilder.Entity("PRN222_Assm.Models.StudentClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<int?>("ScoreId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK_StudentClass_1");

                    b.HasIndex("ClassId");

                    b.HasIndex("ScoreId");

                    b.HasIndex(new[] { "StudentId", "ClassId", "ScoreId" }, "IX_StudentClass")
                        .IsUnique()
                        .HasFilter("[StudentID] IS NOT NULL AND [ScoreId] IS NOT NULL");

                    b.ToTable("StudentClass", (string)null);
                });

            modelBuilder.Entity("PRN222_Assm.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("PRN222_Assm.Models.Attendance", b =>
                {
                    b.HasOne("PRN222_Assm.Models.StudentClass", "Class")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PRN222_Assm.Models.Class", b =>
                {
                    b.HasOne("PRN222_Assm.Models.Semmester", "Semester")
                        .WithMany("Classes")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK_Class_Semmester");

                    b.HasOne("PRN222_Assm.Models.Subject", "SubjectNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("Subject")
                        .HasConstraintName("FK_Class_Subject");

                    b.HasOne("PRN222_Assm.Models.Account", "TearcherNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("Tearcher")
                        .HasConstraintName("FK_Class_Account");

                    b.Navigation("Semester");

                    b.Navigation("SubjectNavigation");

                    b.Navigation("TearcherNavigation");
                });

            modelBuilder.Entity("PRN222_Assm.Models.StudentClass", b =>
                {
                    b.HasOne("PRN222_Assm.Models.Class", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentClass_Class1");

                    b.HasOne("PRN222_Assm.Models.Score", "Score")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ScoreId")
                        .HasConstraintName("FK_StudentClass_Score1");

                    b.HasOne("PRN222_Assm.Models.Account", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_StudentClass_Account1");

                    b.Navigation("Class");

                    b.Navigation("Score");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN222_Assm.Models.Subject", b =>
                {
                    b.HasOne("PRN222_Assm.Models.Category", "CategoryNavigation")
                        .WithMany("Subjects")
                        .HasForeignKey("Category")
                        .HasConstraintName("FK_Subject_Category");

                    b.Navigation("CategoryNavigation");
                });

            modelBuilder.Entity("PRN222_Assm.Models.Account", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("PRN222_Assm.Models.Category", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("PRN222_Assm.Models.Class", b =>
                {
                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("PRN222_Assm.Models.Score", b =>
                {
                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("PRN222_Assm.Models.Semmester", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("PRN222_Assm.Models.StudentClass", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("PRN222_Assm.Models.Subject", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
